### ISSUE TITLE
Nice Job! Source release?

### ISSUE THREAD

**Issue by 2braincells2go** [vladignatyev/crx-extractor#1]
I would love to use this in a classroom environment.

When do you think you will upload the source?

Since internet is very limited in the classroom like to run on local server and provide crx extensions for students to dissect / learn from.

Thanks,

Woody

**Comment by vladignatyev** [comment]
@2braincells2go Hello and thank you for posting an issue! Please excuse me for such big delay in response.

I've just posted the source code, enjoy!

**Comment by 2braincells2go** [comment]
Thank you! Will have to look at and see what it takes to build for a local server.
