### ISSUE TITLE
Support new Chrome webstore URL

### ISSUE THREAD

**Issue by leiless** [vladignatyev/crx-extractor#16]
https://crxextractor.com/

Old: https://chrome.google.com/webstore/detail/custom-cursor-for-chrome/ogdlpmhglpejoiomcodnpjnfgcpmgale

New: https://chromewebstore.google.com/detail/custom-cursor-for-chrome/ogdlpmhglpejoiomcodnpjnfgcpmgale

![image](https://github.com/vladignatyev/crx-extractor/assets/38041294/f8181598-be9d-4845-a371-2cc22e56b313)

**Comment by vladignatyev** [comment]
Thanks for pointing out! I'll update soon. Feel free to fork!

**Comment by vladignatyev** [comment]
@leiless I've just updated the website. Now the new Chrome Webstore URLs supported! Remember to clean cache in your browser to use new updated site!

**Comment by leiless** [comment]
Thank you!
