### ISSUE TITLE
uploaded crx files incorrectly failing verification

### ISSUE THREAD

**Issue by FredThompsonII** [vladignatyev/crx-extractor#4]
I used http://crxextractor.com/ to download a number of extensions. Each of those was dragged to the decompile area, were sent to the host, and...were rejected as being invalid containers. Systems is Win8.1x64 FF56.0.2

Any idea why this is happening and how to prevent the false negatives?

**Comment by vladignatyev** [comment]
@FredThompsonII missed this issue. could you please provide more details, at least example of extensions?

**Comment by upils** [comment]
CRX2 Has been deprecated recently (https://www.chromium.org/crx2-deprecation). Is this related ? Which version do the tool expect ? 

Existing implementation already exist (eg. to generate a CRX3 file https://github.com/ahwayakchih/crx3)

Here is the design doc, specifying the file format https://docs.google.com/document/d/1pAVB4y5EBhqufLshWMcvbQ5velk0yMGl5ynqiorTCG4/edit#heading=h.ke61kmpkapku

**Comment by vladignatyev** [comment]
@upils I'm working on update for Crxextractor. In the meantime will enable support for recent versions of .CRX!
Thanks for update from you! It is a valuable contribution!

**Comment by upils** [comment]
Nice :)
Glad to see this tool is still maintained!

**Comment by legoblokje** [comment]
@vladignatyev any updates? Really like this tool and would love CRX3 support.

**Comment by vladignatyev** [comment]
@legoblokje I'm going to resolve issues this weekend!

**Comment by vladignatyev** [comment]
much appreciate if anybody give me few .crx those are breaking crxextractor!

**Comment by vladignatyev** [comment]
Probably resolved by the latest commit. Check out on the website: https://crxextractor.com/

If you check and it been resolved, please remind me or close this issue!
